Test this on Cheyenne
Added 'or []' because of
   TypeError: 'NoneType' object is not iterable in Python

1235 for skip_comp in skip_comps or []:

Not sure this is the correct thing to do.

compile error on Oscar
test/latest.cime/cime/src/drivers/nuopc/mediator/med_constants_mod.F90
err=ERROR:  No results found for variable CAM_DYCORE
ERROR:  No results found for variable CAM_DYCORE
esmFlds.F90(360): #error: #if: syntax error.